# Generated by Django 3.1.1 on 2020-09-12 02:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('birthdate', models.DateField(blank=True, default=None)),
                ('univ', models.CharField(blank=True, choices=[('중앙대', '중앙대'), ('타 대학', '타 대학'), ('비공개', '비공개')], default='비공개', max_length=10)),
                ('major', models.CharField(blank=True, choices=[('솦트', '솦트'), ('융공', '융공'), ('건공', '건공'), ('비공개', '비공개')], default='비공개', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('비공개', '비공개'), ('남', '남'), ('여', '여')], default=None, max_length=10)),
                ('profile_photo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
