# Generated by Django 3.1 on 2020-08-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200819_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='nickname',
            new_name='title',
        ),
    ]
