# Generated by Django 3.1 on 2020-08-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200819_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='name',
            new_name='author',
        ),
    ]
