# Generated by Django 3.1 on 2020-08-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200819_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
