# Generated by Django 3.1 on 2020-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.AddField(
            model_name='myuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
