# Generated by Django 3.0.5 on 2020-08-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200828_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
