# Generated by Django 3.0.6 on 2020-05-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_login_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='json_time_table',
        ),
    ]
