# Generated by Django 3.0.6 on 2020-05-30 02:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_json_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='json_time_table',
            field=jsonfield.fields.JSONField(default={'Monday': [0, 1, 1, 0, 1, 1], 'Tuesday': [1, 1, 1, 0, 0, 0], 'Wednesday': [0, 0, 1, 0, 1, 1]}),
        ),
    ]
