# Generated by Django 3.0.6 on 2020-05-30 04:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_json_time_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='json_time_table',
        ),
        migrations.AddField(
            model_name='profile',
            name='time_table',
            field=jsonfield.fields.JSONField(default={'Fri': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Mon': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Thu': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Tue': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Wed': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}),
        ),
    ]
