# Generated by Django 3.1 on 2020-08-27 07:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummyname', models.CharField(max_length=30)),
                ('timetable', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('matched_date', models.DateField()),
                ('matched_time', models.TimeField()),
                ('due_date', models.DateTimeField()),
                ('invite_url', models.URLField()),
                ('member_list', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
