# Generated by Django 3.1 on 2020-08-26 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('matched_date', models.DateField()),
                ('matched_time', models.TimeField()),
                ('due_date', models.DateTimeField()),
                ('invite_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', django.contrib.postgres.fields.jsonb.JSONField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummyname', models.CharField(max_length=30)),
                ('meetingResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingresult')),
            ],
        ),
    ]
