# Generated by Django 3.1.3 on 2020-11-21 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_range', jsonfield.fields.JSONField()),
                ('confirmed_date', models.DateTimeField(null=True)),
                ('invite_url', models.URLField(blank=True, null=True)),
                ('member_list', jsonfield.fields.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DummyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', jsonfield.fields.JSONField(blank=True, null=True)),
                ('connected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DummyPlan', to='meeting.plan')),
            ],
        ),
    ]
