# Generated by Django 3.1.3 on 2020-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='invite_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/Plan/<built-in function id>createDummyPlan', null=True),
        ),
    ]
