# Generated by Django 3.1.3 on 2020-11-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='invite_url',
        ),
    ]
