# Generated by Django 3.1 on 2020-08-27 06:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='anonymous',
            field=jsonfield.fields.JSONField(),
        ),
    ]
