# Generated by Django 3.1 on 2020-08-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingResult',
            new_name='MeetingCreate',
        ),
    ]
