# Generated by Django 3.1.3 on 2020-11-20 01:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201120_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date_range',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='invite_url',
            field=models.URLField(null=True),
        ),
    ]
