# Generated by Django 3.1.3 on 2020-11-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201124_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='member_list',
        ),
    ]
