# Generated by Django 3.1.3 on 2020-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201123_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='invite_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
