# Generated by Django 3.1.3 on 2020-11-21 11:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_remove_plan_invite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='invite_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='member_list',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
