# Generated by Django 3.1 on 2020-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20200827_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_date', models.DateField()),
                ('matched_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingcreate',
            name='matched_date',
        ),
        migrations.RemoveField(
            model_name='meetingcreate',
            name='matched_time',
        ),
    ]
