# Generated by Django 3.1 on 2020-08-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20200827_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberlist',
            name='anonymous',
        ),
    ]
