# Generated by Django 3.1.3 on 2020-11-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20201121_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyplan',
            name='connected_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_plans', to='meeting.plan'),
        ),
    ]
