# Generated by Django 3.1 on 2020-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_remove_memberlist_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginput',
            name='meetingResult',
        ),
    ]
