# Generated by Django 3.1 on 2020-08-27 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200827_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginput',
            name='team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingcreate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingcreate'),
            preserve_default=False,
        ),
    ]
