# Generated by Django 3.1 on 2020-08-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20200827_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='team',
        ),
    ]
