# Generated by Django 3.1 on 2020-08-27 07:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_remove_meetinginput_meetingresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberList',
        ),
        migrations.AddField(
            model_name='meetinginput',
            name='timetable',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='meetingresult',
            name='member_list',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
