# Generated by Django 3.1 on 2020-08-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20200827_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginput',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='meetingresult',
            name='member_list',
        ),
    ]
