# Generated by Django 3.1 on 2020-08-31 08:37

from django.db import migrations
import jsonfield.fields
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20200827_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginput',
            name='date',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='meetinginput',
            name='timetable',
            field=jsonfield.fields.JSONField(default=meeting.models.timetable_default),
        ),
        migrations.AlterUniqueTogether(
            name='meetinginput',
            unique_together={('team', 'date', 'dummyname', 'timetable')},
        ),
    ]
