# Generated by Django 3.1 on 2020-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meetingcreate_isonlydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcreate',
            name='isOnlyDate',
        ),
        migrations.AddField(
            model_name='meetingcreate',
            name='settingTime',
            field=models.BooleanField(default=False),
        ),
    ]
