# Generated by Django 3.1 on 2020-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_auto_20200916_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcreate',
            name='settingTime',
        ),
        migrations.AddField(
            model_name='meetingcreate',
            name='isOnlyDate',
            field=models.BooleanField(default=True),
        ),
    ]
