# Generated by Django 3.1 on 2020-09-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_auto_20200916_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='matched_time',
            field=models.TimeField(null=True),
        ),
    ]
